#ifndef PORT_CFG_H
#define PORT_CFG_H

#define PORT_CFG_MODULE_ID
#define PORT_CFG_VENDOR_ID

#define PORT_CFG_SW_MAJOR_VERSION 1U
#define PORT_CFG_SW_MINOR_VERSION 0U
#define PORT_CFG_SW_PATCH_VERSION 0U

#define PORT_CFG_AR_RELEASE_MAJOR_VERSION 21U
#define PORT_CFG_AR_RELEASE_MINOR_VERSION 11U
#define PORT_CFG_AR_RELEASE_PATCH_VERSION 0U

#include "Std_Types.h"

/* AUTOSAR checking between Std_Types and Port_Cfg Modules */
#if ((STD_TYPES_AR_RELEASE_MAJOR_VERSION != \
      PORT_CFG_AR_RELEASE_MAJOR_VERSION) || \
     (STD_TYPES_AR_RELEASE_MINOR_VERSION != \
      PORT_CFG_AR_RELEASE_MINOR_VERSION) || \
     (STD_TYPES_AR_RELEASE_PATCH_VERSION != \
      PORT_CFG_AR_RELEASE_PATCH_VERSION))
#error "The AR version of Std_Types.h does not match the expected version"
#endif

/*
 * Module Wide Configurations
 * */
#define PORT_DEV_ERR_DETECT STD_OFF
#define PORT_SET_PIN_DIRECTION_API STD_ON
#define PORT_SET_PIN_MODE_API STD_ON
#define PORT_VERSION_INFO_API STD_ON

/*
 * Number of Ports
 * */
#define PORT_NUM_OF_PORTS 6U

/*
 * Pin Modes
 * */
#define PORT_PIN_MODE_CAN           0x00U
#define PORT_PIN_MODE_DIO           0x01U
#define PORT_PIN_MODE_DIO_GPT       0x02U
#define PORT_PIN_MODE_ICU           0x03U
#define PORT_PIN_MODE_SSI           0x04U
#define PORT_PIN_MODE_PWM           0x05U
#define PORT_PIN_MODE_QEI           0x06U
#define PORT_PIN_MODE_UART          0x07U
#define PORT_PIN_MODE_UART_FLOW_CTL 0x08U
#define PORT_PIN_MODE_NMI           0x09U
#define PORT_PIN_MODE_I2C           0x0AU
#define PORT_PIN_MODE_HIBERNATE     0x0BU
#define PORT_PIN_MODE_OSC           0x0CU
#define PORT_PIN_MODE_JTAG          0x0DU
#define PORT_PIN_MODE_ADC           0x0EU
#define PORT_PIN_MODE_USB           0x0FU
#define PORT_PIN_MODE_ANALOG_COMP   0x10U

/*
 * Pin Levels
 * */
#define PORT_PIN_LEVEL_LOW 0x00U
#define PORT_PIN_LEVEL_HIGH 0x01U

/*
 * Pin Drive Modes
 * */
#define PORT_PIN_DRIVE_PUSH_PULL 0x00U
#define PORT_PIN_DRIVE_OPEN_DRAIN 0x01U

/*
 * Pin Pad Drive Modes
 * */
#define PORT_PIN_PAD_DRIVE_2MA 0x00U
#define PORT_PIN_PAD_DRIVE_4MA 0x01U
#define PORT_PIN_PAD_DRIVE_8MA 0x02U

/*
 * Number of Pins for Each Port
 * */
#define PORT_A_NUMBER_OF_PORT_PINS 8U
#define PORT_B_NUMBER_OF_PORT_PINS 8U
#define PORT_C_NUMBER_OF_PORT_PINS 8U
#define PORT_D_NUMBER_OF_PORT_PINS 8U
#define PORT_E_NUMBER_OF_PORT_PINS 6U
#define PORT_F_NUMBER_OF_PORT_PINS 5U

/*
 * Port IDs
 * */
#define PORT_A_ID   0U
#define PORT_B_ID   1U
#define PORT_C_ID   2U
#define PORT_D_ID   3U
#define PORT_E_ID   4U
#define PORT_F_ID   5U

/*
 * Pins IDs
 * */
#define PORT_A_PIN_0_ID 0x00U
#define PORT_A_PIN_1_ID 0x01U
#define PORT_A_PIN_2_ID 0x02U
#define PORT_A_PIN_3_ID 0x03U
#define PORT_A_PIN_4_ID 0x04U
#define PORT_A_PIN_5_ID 0x05U
#define PORT_A_PIN_6_ID 0x06U
#define PORT_A_PIN_7_ID 0x07U

#define PORT_B_PIN_0_ID 0x10U
#define PORT_B_PIN_1_ID 0x11U
#define PORT_B_PIN_2_ID 0x12U
#define PORT_B_PIN_3_ID 0x13U
#define PORT_B_PIN_4_ID 0x14U
#define PORT_B_PIN_5_ID 0x15U
#define PORT_B_PIN_6_ID 0x16U
#define PORT_B_PIN_7_ID 0x17U

#define PORT_C_PIN_0_ID 0x20U
#define PORT_C_PIN_1_ID 0x21U
#define PORT_C_PIN_2_ID 0x22U
#define PORT_C_PIN_3_ID 0x23U
#define PORT_C_PIN_4_ID 0x24U
#define PORT_C_PIN_5_ID 0x25U
#define PORT_C_PIN_6_ID 0x26U
#define PORT_C_PIN_7_ID 0x27U

#define PORT_D_PIN_0_ID 0x30U
#define PORT_D_PIN_1_ID 0x31U
#define PORT_D_PIN_2_ID 0x32U
#define PORT_D_PIN_3_ID 0x33U
#define PORT_D_PIN_4_ID 0x34U
#define PORT_D_PIN_5_ID 0x35U
#define PORT_D_PIN_6_ID 0x36U
#define PORT_D_PIN_7_ID 0x37U

#define PORT_E_PIN_0_ID 0x40U
#define PORT_E_PIN_1_ID 0x41U
#define PORT_E_PIN_2_ID 0x42U
#define PORT_E_PIN_3_ID 0x43U
#define PORT_E_PIN_4_ID 0x44U
#define PORT_E_PIN_5_ID 0x45U

#define PORT_F_PIN_0_ID 0x50U
#define PORT_F_PIN_1_ID 0x51U
#define PORT_F_PIN_2_ID 0x52U
#define PORT_F_PIN_3_ID 0x53U
#define PORT_F_PIN_4_ID 0x54U

///*
// * Pins Direction
// * */
// #define PORT_A_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_1_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_2_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_3_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_4_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_5_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_6_DIRECTION      PORT_PIN_IN
// #define PORT_A_PIN_7_DIRECTION      PORT_PIN_IN
//
// #define PORT_B_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_1_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_2_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_3_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_4_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_5_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_6_DIRECTION      PORT_PIN_IN
// #define PORT_B_PIN_7_DIRECTION      PORT_PIN_IN
//
// #define PORT_C_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_1_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_2_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_3_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_4_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_5_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_6_DIRECTION      PORT_PIN_IN
// #define PORT_C_PIN_7_DIRECTION      PORT_PIN_IN
//
// #define PORT_D_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_1_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_2_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_3_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_4_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_5_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_6_DIRECTION      PORT_PIN_IN
// #define PORT_D_PIN_7_DIRECTION      PORT_PIN_IN
//
// #define PORT_E_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_E_PIN_1_DIRECTION      PORT_PIN_IN
// #define PORT_E_PIN_2_DIRECTION      PORT_PIN_IN
// #define PORT_E_PIN_3_DIRECTION      PORT_PIN_IN
// #define PORT_E_PIN_4_DIRECTION      PORT_PIN_IN
// #define PORT_E_PIN_5_DIRECTION      PORT_PIN_IN
//
// #define PORT_F_PIN_0_DIRECTION      PORT_PIN_IN
// #define PORT_F_PIN_1_DIRECTION      PORT_PIN_IN
// #define PORT_F_PIN_2_DIRECTION      PORT_PIN_IN
// #define PORT_F_PIN_3_DIRECTION      PORT_PIN_IN
// #define PORT_F_PIN_4_DIRECTION      PORT_PIN_IN
//
/*
 * Pins Direction Changeability
 * */
#define PORT_A_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_1_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_2_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_3_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_4_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_5_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_6_DIRECTION_CHANGEABLE TRUE
#define PORT_A_PIN_7_DIRECTION_CHANGEABLE TRUE

#define PORT_B_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_1_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_2_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_3_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_4_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_5_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_6_DIRECTION_CHANGEABLE TRUE
#define PORT_B_PIN_7_DIRECTION_CHANGEABLE TRUE

#define PORT_C_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_1_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_2_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_3_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_4_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_5_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_6_DIRECTION_CHANGEABLE TRUE
#define PORT_C_PIN_7_DIRECTION_CHANGEABLE TRUE

#define PORT_D_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_1_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_2_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_3_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_4_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_5_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_6_DIRECTION_CHANGEABLE TRUE
#define PORT_D_PIN_7_DIRECTION_CHANGEABLE TRUE

#define PORT_E_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_E_PIN_1_DIRECTION_CHANGEABLE TRUE
#define PORT_E_PIN_2_DIRECTION_CHANGEABLE TRUE
#define PORT_E_PIN_3_DIRECTION_CHANGEABLE TRUE
#define PORT_E_PIN_4_DIRECTION_CHANGEABLE TRUE
#define PORT_E_PIN_5_DIRECTION_CHANGEABLE TRUE

#define PORT_F_PIN_0_DIRECTION_CHANGEABLE TRUE
#define PORT_F_PIN_1_DIRECTION_CHANGEABLE TRUE
#define PORT_F_PIN_2_DIRECTION_CHANGEABLE TRUE
#define PORT_F_PIN_3_DIRECTION_CHANGEABLE TRUE
#define PORT_F_PIN_4_DIRECTION_CHANGEABLE TRUE

///*
// * Pins Initial Mode
// * */
// #define PORT_A_PIN_0_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_1_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_2_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_3_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_4_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_5_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_6_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_A_PIN_7_INITIAL_MODE   PORT_PIN_MODE_DIO
//
// #define PORT_B_PIN_0_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_1_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_2_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_3_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_4_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_5_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_6_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_B_PIN_7_INITIAL_MODE   PORT_PIN_MODE_DIO
//
// #define PORT_C_PIN_0_INITIAL_MODE   PORT_PIN_MODE_JTAG
// #define PORT_C_PIN_1_INITIAL_MODE   PORT_PIN_MODE_JTAG
// #define PORT_C_PIN_2_INITIAL_MODE   PORT_PIN_MODE_JTAG
// #define PORT_C_PIN_3_INITIAL_MODE   PORT_PIN_MODE_JTAG
// #define PORT_C_PIN_4_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_C_PIN_5_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_C_PIN_6_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_C_PIN_7_INITIAL_MODE   PORT_PIN_MODE_DIO
//
// #define PORT_D_PIN_0_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_1_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_2_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_3_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_4_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_5_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_6_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_D_PIN_7_INITIAL_MODE   PORT_PIN_MODE_NMI
//
// #define PORT_E_PIN_0_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_E_PIN_1_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_E_PIN_2_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_E_PIN_3_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_E_PIN_4_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_E_PIN_5_INITIAL_MODE   PORT_PIN_MODE_DIO
//
// #define PORT_F_PIN_0_INITIAL_MODE   PORT_PIN_MODE_NMI
// #define PORT_F_PIN_1_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_F_PIN_2_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_F_PIN_3_INITIAL_MODE   PORT_PIN_MODE_DIO
// #define PORT_F_PIN_4_INITIAL_MODE   PORT_PIN_MODE_DIO
//
///*
// * Pins Modes
// * */
// #define PORT_A_PIN_0_MODE_0 PORT_PIN_MODE_DIO
// #define PORT_A_PIN_0_MODE_1 PORT_PIN_MODE_UART
// #define PORT_A_PIN_0_MODE_2 PORT_PIN_MODE_CAN
//
// #define PORT_A_PIN_1_MODE_0 PORT_PIN_MODE_DIO
// #define PORT_A_PIN_1_MODE_1 PORT_PIN_MODE_UART
// #define PORT_A_PIN_1_MODE_2 PORT_PIN_MODE_CAN
//
// #define PORT_A_PIN_2_MODE_0 PORT_PIN_MODE_DIO
// #define PORT_A_PIN_2_MODE_1 PORT_PIN_MODE_SSI
//
// #define PORT_A_PIN_3_MODE_0 PORT_PIN_MODE_DIO
// #define PORT_A_PIN_3_MODE_1 PORT_PIN_MODE_SSI
//
// #define PORT_A_PIN_4_MODE_0 PORT_PIN_MODE_DIO
// #define PORT_A_PIN_4_MODE_1 PORT_PIN_MODE_SSI
//
// #define PORT_A_PIN_5_MODE_0 PORT_PIN_MODE_DIO
// #define PORT_A_PIN_5_MODE_1 PORT_PIN_MODE_SSI
//
/*
 * Pins Mode Changeability
 * */
#define PORT_A_PIN_0_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_1_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_2_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_3_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_4_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_5_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_6_MODE_CHANGEABLE TRUE
#define PORT_A_PIN_7_MODE_CHANGEABLE TRUE

#define PORT_B_PIN_0_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_1_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_2_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_3_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_4_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_5_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_6_MODE_CHANGEABLE TRUE
#define PORT_B_PIN_7_MODE_CHANGEABLE TRUE

#define PORT_C_PIN_0_MODE_CHANGEABLE FALSE
#define PORT_C_PIN_1_MODE_CHANGEABLE FALSE
#define PORT_C_PIN_2_MODE_CHANGEABLE FALSE
#define PORT_C_PIN_3_MODE_CHANGEABLE FALSE
#define PORT_C_PIN_4_MODE_CHANGEABLE TRUE
#define PORT_C_PIN_5_MODE_CHANGEABLE TRUE
#define PORT_C_PIN_6_MODE_CHANGEABLE TRUE
#define PORT_C_PIN_7_MODE_CHANGEABLE TRUE

#define PORT_D_PIN_0_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_1_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_2_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_3_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_4_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_5_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_6_MODE_CHANGEABLE TRUE
#define PORT_D_PIN_7_MODE_CHANGEABLE TRUE

#define PORT_E_PIN_0_MODE_CHANGEABLE TRUE
#define PORT_E_PIN_1_MODE_CHANGEABLE TRUE
#define PORT_E_PIN_2_MODE_CHANGEABLE TRUE
#define PORT_E_PIN_3_MODE_CHANGEABLE TRUE
#define PORT_E_PIN_4_MODE_CHANGEABLE TRUE
#define PORT_E_PIN_5_MODE_CHANGEABLE TRUE

#define PORT_F_PIN_0_MODE_CHANGEABLE TRUE
#define PORT_F_PIN_1_MODE_CHANGEABLE TRUE
#define PORT_F_PIN_2_MODE_CHANGEABLE TRUE
#define PORT_F_PIN_3_MODE_CHANGEABLE TRUE
#define PORT_F_PIN_4_MODE_CHANGEABLE TRUE

///*
// * Pins Level
// * */
// #define PORT_A_PIN_0_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_1_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_2_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_3_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_4_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_5_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_6_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_A_PIN_7_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
//
// #define PORT_B_PIN_0_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_1_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_2_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_3_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_4_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_5_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_6_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_B_PIN_7_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
//
// #define PORT_C_PIN_0_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_1_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_2_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_3_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_4_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_5_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_6_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_C_PIN_7_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
//
// #define PORT_D_PIN_0_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_1_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_2_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_3_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_4_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_5_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_6_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_D_PIN_7_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
//
// #define PORT_E_PIN_0_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_E_PIN_1_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_E_PIN_2_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_E_PIN_3_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_E_PIN_4_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_E_PIN_5_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
//
// #define PORT_F_PIN_0_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_F_PIN_1_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_F_PIN_2_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_F_PIN_3_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
// #define PORT_F_PIN_4_LEVEL_VALUE    PORT_PIN_LEVEL_LOW
//
///*
// * Pin Slew Rate Control
// * */
// #define PORT_A_PIN_0_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_1_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_2_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_3_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_4_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_5_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_6_SLEW_RATE_CTL  STD_OFF
// #define PORT_A_PIN_7_SLEW_RATE_CTL  STD_OFF
//
// #define PORT_B_PIN_0_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_1_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_2_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_3_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_4_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_5_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_6_SLEW_RATE_CTL  STD_OFF
// #define PORT_B_PIN_7_SLEW_RATE_CTL  STD_OFF
//
// #define PORT_C_PIN_0_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_1_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_2_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_3_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_4_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_5_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_6_SLEW_RATE_CTL  STD_OFF
// #define PORT_C_PIN_7_SLEW_RATE_CTL  STD_OFF
//
// #define PORT_D_PIN_0_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_1_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_2_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_3_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_4_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_5_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_6_SLEW_RATE_CTL  STD_OFF
// #define PORT_D_PIN_7_SLEW_RATE_CTL  STD_OFF
//
// #define PORT_E_PIN_0_SLEW_RATE_CTL  STD_OFF
// #define PORT_E_PIN_1_SLEW_RATE_CTL  STD_OFF
// #define PORT_E_PIN_2_SLEW_RATE_CTL  STD_OFF
// #define PORT_E_PIN_3_SLEW_RATE_CTL  STD_OFF
// #define PORT_E_PIN_4_SLEW_RATE_CTL  STD_OFF
// #define PORT_E_PIN_5_SLEW_RATE_CTL  STD_OFF
//
// #define PORT_F_PIN_0_SLEW_RATE_CTL  STD_OFF
// #define PORT_F_PIN_1_SLEW_RATE_CTL  STD_OFF
// #define PORT_F_PIN_2_SLEW_RATE_CTL  STD_OFF
// #define PORT_F_PIN_3_SLEW_RATE_CTL  STD_OFF
// #define PORT_F_PIN_4_SLEW_RATE_CTL  STD_OFF
//
///*
// * Pin Drive Mode
// * */
// #define PORT_A_PIN_0_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_1_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_2_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_3_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_4_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_5_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_6_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_A_PIN_7_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
//
// #define PORT_B_PIN_0_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_1_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_2_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_3_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_4_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_5_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_6_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_B_PIN_7_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
//
// #define PORT_C_PIN_0_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_1_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_2_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_3_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_4_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_5_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_6_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_C_PIN_7_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
//
// #define PORT_D_PIN_0_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_1_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_2_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_3_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_4_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_5_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_6_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_D_PIN_7_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
//
// #define PORT_E_PIN_0_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_E_PIN_1_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_E_PIN_2_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_E_PIN_3_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_E_PIN_4_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_E_PIN_5_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
//
// #define PORT_F_PIN_0_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_F_PIN_1_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_F_PIN_2_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_F_PIN_3_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
// #define PORT_F_PIN_4_DRIVE  PORT_PIN_DRIVE_PUSH_PULL
//
///*
// * Pin Pad Drive
// * */
// #define PORT_A_PIN_0_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_1_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_2_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_3_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_4_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_5_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_6_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_A_PIN_7_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
//
// #define PORT_B_PIN_0_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_1_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_2_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_3_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_4_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_5_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_6_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_B_PIN_7_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
//
// #define PORT_C_PIN_0_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_1_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_2_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_3_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_4_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_5_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_6_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_C_PIN_7_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
//
// #define PORT_D_PIN_0_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_1_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_2_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_3_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_4_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_5_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_6_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_D_PIN_7_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
//
// #define PORT_E_PIN_0_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_E_PIN_1_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_E_PIN_2_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_E_PIN_3_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_E_PIN_4_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_E_PIN_5_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
//
// #define PORT_F_PIN_0_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_F_PIN_1_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_F_PIN_2_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_F_PIN_3_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
// #define PORT_F_PIN_4_PAD_DRIVE  PORT_PIN_PAD_DRIVE_2MA
//
///*
// * Pin Internal Pull-Up Activation
// * */
// #define PORT_A_PIN_0_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_1_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_2_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_3_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_4_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_5_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_6_PULL_UP_ACTIVE     FALSE
// #define PORT_A_PIN_7_PULL_UP_ACTIVE     FALSE
//
// #define PORT_B_PIN_0_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_1_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_2_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_3_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_4_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_5_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_6_PULL_UP_ACTIVE     FALSE
// #define PORT_B_PIN_7_PULL_UP_ACTIVE     FALSE
//
// #define PORT_C_PIN_0_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_1_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_2_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_3_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_4_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_5_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_6_PULL_UP_ACTIVE     FALSE
// #define PORT_C_PIN_7_PULL_UP_ACTIVE     FALSE
//
// #define PORT_D_PIN_0_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_1_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_2_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_3_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_4_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_5_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_6_PULL_UP_ACTIVE     FALSE
// #define PORT_D_PIN_7_PULL_UP_ACTIVE     FALSE
//
// #define PORT_E_PIN_0_PULL_UP_ACTIVE     FALSE
// #define PORT_E_PIN_1_PULL_UP_ACTIVE     FALSE
// #define PORT_E_PIN_2_PULL_UP_ACTIVE     FALSE
// #define PORT_E_PIN_3_PULL_UP_ACTIVE     FALSE
// #define PORT_E_PIN_4_PULL_UP_ACTIVE     FALSE
// #define PORT_E_PIN_5_PULL_UP_ACTIVE     FALSE
//
// #define PORT_F_PIN_0_PULL_UP_ACTIVE     FALSE
// #define PORT_F_PIN_1_PULL_UP_ACTIVE     FALSE
// #define PORT_F_PIN_2_PULL_UP_ACTIVE     FALSE
// #define PORT_F_PIN_3_PULL_UP_ACTIVE     FALSE
// #define PORT_F_PIN_4_PULL_UP_ACTIVE     FALSE

#endif /* PORT_CFG_H */
